name: Build Client App

defaults:
  run:
    working-directory: ./client

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build && npm run lint

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-app
          path: ./client/dist/