name: Build Server App

defaults:
    run:
        working-directory: .

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Build app
              run: npm run build

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test:ci

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: server-app
                  path: ./dist/
